name: SwiftUiView
options:
  deploymentTarget:
    iOS: '16.0'
  localizations:
    - language: ja
      path: "SwiftUiView/ja.lproj" # 日本語ローカライズ
    - language: en
      path: "SwiftUiView/en.lproj" # 英語ローカライズ
  postGenCommand: pod install

targets:
  SwiftUiView:
    type: application
    platform: iOS
    deploymentTarget: '16.0'
    sources: [SwiftUiView]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.w.kot.SwiftUiView
        INFO_PLIST_FILE: Info.plist  # Info.plistファイルを指定
